src/psi/j/executors/__init__.py
src/psi/j/executors/rp.py
tests/run_local_job.py

As the title says, it's a quick attempt on an RP executor.  You'd need to `pip install radical.pilot` to get it to work, and you'll need to set `RADICAL_PILOT_DBURL` to point to a usable MongoDB.

quick & dirty RP executor

---

setup.py

Fix setuptools develop installs

---

requirements-dev.txt

Added minimum requirement for pytest, to address #102

---

QuickStart.md
README.md

Pull from fork Wilke/quick start

---

src/psij-descriptors/aprun_descriptor.py
src/psij-descriptors/cobalt_descriptor.py
src/psij-descriptors/core_descriptors.py
src/psij-descriptors/flux_descriptor.py
src/psij-descriptors/jsrun_descriptor.py
src/psij-descriptors/lsf_descriptor.py
src/psij-descriptors/rp_descriptor.py
src/psij-descriptors/saga_descriptor.py
src/psij-descriptors/slurm_descriptor.py
src/psij-descriptors/srun_descriptor.py
src/psij/__init__.py
src/psij/_plugins.py
src/psij/descriptor.py
src/psij/job_executor.py
src/psij/launchers/launcher.py
tests/plugins1/psij-descriptors/descriptors.py

A big diff for a small change ;)

Remove underscore prefixes from psij._descriptor._Descriptor

---

setup.py

Reading requirements from file.

Read requirements file

---

src/psij/executors/flux.py
tests/conftest.py
tests/test_executor.py

Closes #52 
Closes #18 
Closes #31 
Closes #50

Flux executor rewrite

---

requirements-dev.txt
requirements.txt
src/psij/descriptor.py
src/psij/executors/batch/pbspro.py
src/psij/job_spec.py
src/psij/job_state.py
src/psij/serialize.py
src/psij/utils.py

This enables additional checks for docstring formatting.
The PR also contains some docstring fixes to make it actually work.

Add flake8 docstrings

---

web/index.html
web/style.css
web/theme-4.css

This PR does not change the way the site looks, but moves some CSS around, merges some styles in existing selectors, and removes some unused CSS.

Re-organized CSS a little

---

docs/getting_started.rst
docs/index.rst

Also add a supported scheduler list to the documentation index.rst

Add API links to getting_started page

---

web/theme-4.css

Change color of selected tab line to something that's visible.

---

src/psij/job_spec.py
src/psij/serialize.py

Closes #194  Added export functionality for ResourceSpec

Added handling of ResourceSpecV1

---

web/lib.js

Docs are currently broken because the JS code didn't account for the fact that the current site does is not at the root at the domain. This PR fixes that.

Fix for when the PSI/J site is not at the root of the web path.

---

src/psij/executors/batch/pbspro/pbspro.mustache

Add a couple of missing attributes to PBS submit script template.

---

src/psij/serialize.py

make mandatory args not-optional, raise `TypeError` on type errors

---

docs/getting_started.rst
tests/test_doc_examples.py

It didn't make sense to me to test some of the code snippets in the quickstart guide, and this was the best alternative I could think of.

Improve docs tests

---

QuickStart.md
README-testing.md
README.md
docs/getting_started.rst
src/psij/executors/batch/pbspro.py
src/psij/launchers/aprun.py
src/psij/launchers/jsrun.py
src/psij/launchers/srun.py

Addresses comments and concerns from https://docs.google.com/document/d/1rKHOPSUpys9wTooSLsisZRGRVUvGqufQ3iP8RbxpEmw/edit

docs and docstrings: fix typos

---

requirements-dev.txt
requirements-tests.txt

This should address #283.
@wilke, can you try setting up the tests with this branch?

Make req-dev include req-tests and add requests explicitly to req-tests

---

src/psij/job_executor_config.py
tests/plugins1/_batch_test/_batch_test.py

ensure that workdir is converted to `Path` type

---

src/psij/job_spec.py

Not sure what happened there

---

src/psij/executors/local.py

polling at fixed intervals of 0.2s. Without it, `/bin/sleep 0` would take a minimum of 0.2s to complete, which is unnecessary. With the change, the same takes 0.013s instead. Still too much if you ask me.

Catch SIGCHLD to figure out when a child process completes instead of

---

src/psij/launchers/script_based_launcher.py

Set deployed flag after deploying

---

src/psij/job_attributes.py
src/psij/serialize.py

JobAttributes and make it public.

Move the walltime parsing routine in the serialiation module to

---

README-testing.md
psij-ci-setup
testing.conf
tests/conftest.py

This is to go with https://github.com/ExaWorks/psij-testing-service/pull/57

Use auth keys for test uploads

---

src/psij/executors/batch/batch_scheduler_executor.py
src/psij/executors/batch/lsf.py
tests/test_issue_435.py

Fix walltime float hours

---

.gitignore
src/psij/executors/batch/cobalt.py
src/psij/executors/batch/lsf.py
src/psij/executors/batch/pbs_base.py
src/psij/executors/batch/slurm.py
src/psij/job_attributes.py

Documented custom attributes a bit better

---

requirements.txt
src/psij/job_attributes.py
src/psij/job_spec.py
src/psij/resource_spec.py
tests/test_job_spec.py

typeguard update

---

src/psij/executors/batch/pbs_base.py

The "comment" field is not necessarily present for all states.

---

src/psij/executors/batch/batch_scheduler_executor.py

Fixed incorrect order of parameters in BatchSchedulerExecutorConfig
