- .github/workflows/python-package.yml
- Makefile
- requirements-dev.txt
- src/psi/j/executors/local.py
- tests/test_local_jobs.py
The problem was caused by "from __future__ import annotations", which is there to support forward type definitions (e.g., `class A: def fn(a: A):...` instead of having to quote A - `class A: def fn(a: 'A'):...`)
> 3.6 compatibility

- src/psi/j/job_executor.py
Fixed an error in which nested paths in PYTHONPATH can lead to the same executor being loaded twice, which can lead to an executor loading error
> Fixed a nested path executor loading issue

- .mypy
- src/psi/j/executors/rp.py
- src/psi/j/job_executor.py
This PR  attempts to fix the mypy linting errors in the RP connector.  It also adds the missing `psi.j.job_executor.list()` stub which mypy complained about.
The linter still fails because it cannot import the radical modules - they are not installed as dependency.  Even if installed, mypy wil still complain because the radical modules do not use type hints.  How should we handle this?
> linting rp connector

- .github/workflows/python-package.yml
- CONTRIBUTING.md
- Makefile
- docs/conf.py
- requirements-connector-radical.txt
- requirements-dev.txt
- requirements-docs.txt
- src/psi/j/executors/rp.py
- src/psi/j/job_executor_config.py
- src/psi/j/launchers/script_based_launcher.py
- Copy the CONTRIBUTING guide from the SDK repo
- add notes to CONTRIBUTING about the docstring format, type annotations, and code style
- add a make target for `autopep8`, add it to the dev-requirements.txt, and run it on the codebase
- fix `make docs` build due to docstring syntax errors
Closes #20
Closes #21
Closes #22
> Code style etc

- Makefile
- src/psi/j/executors/local.py
- src/psi/j/launchers/launcher.py
- src/psi/j/launchers/script_based_launcher.py
- src/psi/j/launchers/scripts/lib.sh
- src/psi/j/launchers/scripts/mpi_launch.sht
- src/psi/j/launchers/scripts/multi_launch.sht
- src/psi/j/launchers/scripts/single_launch.sht
Commit 47ce6db describes the general problem in more detail.
In addition, this PR removes comments in launcher script templates. The templates are processed with the C pre-processor. On linux with somewhat recent versions of GCC, the default behavior is to remove comments from the output. On OS X, the default `cpp` seems to be the LLVM clang compiler, which keeps comments after pre-processing. These comments, however, are not valid comments in a script. So this should also fix #25.
> Properly handle launcher errors

- Makefile
- docs/conf.py
Problem: when the documentation is built by ReadTheDocs with Sphinx, they (RTD) do not run autodoc first, resulting in a mostly empty doc site.
Solution: follow the workaround prescribed in readthedocs/readthedocs.org#1139 and add code to the conf.py to run autodoc as part of the normal sphinx build process. Also simplify the Makefile based on this new implicit build.
Closes #32
> ReadTheDocs: enable automatic apidoc run/generation

- Makefile
- setup.py
- src/psi/j/launchers/scripts/lib.sh
- src/psi/j/launchers/scripts/mpi_launch.sht
- src/psi/j/launchers/scripts/multi_launch.sht
- src/psi/j/launchers/scripts/single_launch.sht
The launcher scripts are now generated during `setup.py build` and the generation happens in `setup.py`, which also gets a new command named `launcher-scripts`. The `Makefile` target with the same name remains, but now points to `setup.py`.
> Remove gcc dependency

- .gitignore
- src/psi/j/job_executor.py
- tests/test_executor_versions.py
Fix executors' `version` property getter.
Oh, and I snuck a gitignore change in since `make` creates a `build` directory that git wants to track by default.
Closes #41
> Fix `version` accessor

- src/psij/executors/__init__.py
- src/psij/executors/batch/batch_scheduler_executor.py
- src/psij/executors/batch/cobalt/cobalt.mustache
- src/psij/executors/batch_test.py
- src/psij/executors/cobalt.py
- src/psij/executors/lsf.py
- src/psij/executors/slurm.py
Adds a Cobalt executor. There are a fair number of PSI/J options not currently implemented/supported in the mustache script. A big one is the environment inheritance. I don't have much of an account on ALCF or much experience with Cobalt so help debugging/testing would be great.
At the moment I get:
```
Polling error: Failed to poll for job status. Error from status command: Unknown error
Polling error: Failed to poll for job status. Error from status command: Unknown error
Polling error: Failed to poll for job status. Error from status command: Unknown error
Success job finished with JobStatus[FAILED, time=1634951694.098435, message=Failed to poll for job status. Error from status command: Unknown error]
```
Not very helpful...
We will also need a Cobalt launcher (#58).
> Add Cobalt executor

- Makefile
- README-testing.md
- psij-ci-run
- psij-ci-setup
- requirements-connector-saga.txt
- requirements-dev.txt
- requirements.txt
- testing.conf
- tests/ci_runner.py
- tests/conftest.py
- tests/executor_test_params.py
- tests/run_job.py
- tests/test_executor.py
- tests/test_executor_versions.py
- tests/test_infrastructure.py
This PR adds remote test capabilities. There are a few components:
- test output/log capture, which happens in conftest.py
- save/uploads to a testing server, also in conftest.py if requested
- a "ci-runner" (for lack of a better name), which, using testing.conf can clone the git repo, run tests on some branches, and upload the results to said testing server
There is a corresponding server in the psi-j-testing-server repo. It is currently deployed on GCE at testing.exaworks.org, which, incidentally, can also be used to visualize test results.
> Remote testing

- src/psij/launchers/scripts/lib.sh
- tests/conftest.py
This applies to launcher logs and logs when running tests. We may want to have the launcher logs follow whatever timezone is used for the normal logs in the future.
> Logging times in utc

- psij-ci-run
- psij-ci-setup
- requirements-tests.txt
- tests/ci_runner.py
This PR contains a bunch of more-or-less minor updates to testing:
- always check out a current ci-runner from main
- move non-venv non-conda dep installs from --user to .packages inside the testing setup dir
- install/upgrade dependencies on every branch that is tested
- add a requirements-tests.txt, which installs only dependencies needed for testing
> Testing updates

- psij-ci-run
- psij-ci-setup
Not all systems actually start the cron daemon, so cron is really not a given. This PR provides a gnu screen based alternative to running the tests, and, as a fallback, instructions to run the test loop manually.
> Alternative test run method to cron

- src/psij/launchers/script_based_launcher.py
On non-clusters, the existing code works. On clusters, when tests are
run from a non-shared FS, the path inside the source to the launchers
is not visible from CNs, so things fail.
> Invoke launcher with actual deployed path rather than the source path.

- requirements-dev.txt
- requirements-docs.txt
- requirements.txt
The PyPI pystache packages has been taken over by another developer who is now actively maintaining it. This version is also now compatible with newer versions of Python (3.6+).
Additionally, this PR reorganizes the requirements files a bit to make them consistent and reduce duplication.
> Switch back to official pystache

- .github/workflows/python-package.yml
- setup.py
Fixes #123.
Python 3.6 has reached its EOL.
> Increase python version requirement from >=3.6 to >=3.7

- psij-ci-run
- tests/ci_runner.py
With AT as a scheduler for running tests, psij-ci-run would, before every scheduling command, do `export PYTHONPATH=.packages:$PYTHONPATH`. Then AT would pick that up and invoke psij-ci-run with the updated `PYTHONPATH` in the next iteration. In time, `PYTHONPATH` would become larger than the OS limits.
This was fine until tests started requiring the addition of a path to PYTHONPATH, which, done in branch_test_wrapper.sh (without set -e) would silently fail.
This PR also adds the following to the ci tools:
- selectively pass config options in ci-runner; this is necessary if new pass-through attributes are added to ci-runner, but without a corresponding update of testing.conf, a scenario which can very well occur with automated tests
- use https:// to update ci-runner from psij-ci-run; …
> Fix exploding pythonpath

- setup.py
This allows user packages (in my case, the parsl provider) to be checked against type annotations of psij code, when mypy is used when developing those user packages.
This is in contrast to the existing use of mypy and type annotations in psij, which checks that psij is internally self-consistent.
> Export type annotations (PEP 561)

- README-testing.md
- psij-ci-load
- psij-ci-run
- psij-ci-setup
This fixes #148, and #149. It also updates the testing readme and removes the automatic loading of `psij-ci-load` by `psij-ci-setup` (but not `psij-ci-run`).
> Ci updates

- docs/tutorial_add_executor.rst
This built ok before recent `main` merge although I'm unclear what changed.
> Fix block that previously built ok with 2-space indents and now needs 4-space indents

- src/psij/executors/batch/batch_scheduler_executor.py
Fail jobs if `get_status_command` did not yield any usable output, at all, either because the executor was not able to form the correct command or because psij was not able to run it.  In these cases  re-trying would be useless.
This PR though enables a retry if the command did, in fact, yield some output, even if that output may be faulty or incomplete.  We assume here that this could be caused by an intermittent error of the batch system (node overloaded, batch system unresponsive, etc.), and that a retry has a chance of success.
This PR fixes #144.
> handle errors in status loop of batch schedulers

- src/psij/executors/batch/batch_scheduler_executor.py
- src/psij/executors/flux.py
- src/psij/executors/local.py
- src/psij/executors/rp.py
- src/psij/executors/saga.py
- src/psij/job.py
- src/psij/job_executor.py
`job.status` setter.
Renamed `job._executor` into a public property, `job.executor` and moved
the responsibility of setting it to executors (in the `subbmit` and
`attach` methods)
Cleaned up some status setting utility methods in executors.
Fixes #48.
> Removed `job._set_status` and integrated that functionality in the

- docs/getting_started.rst
- docs/index.rst
- docs/installation.rst
I should probably add a one-sentence section about installation: ``pip install psi-j-python``. Since that's all there is to it, right?
> docs: add basic usage guide to sphinx docs

- web/docs/_static/cloud.css
- web/index.html
- web/style.css
- web/theme-4.css
This PR changes the main font from Gill Sans to something more in-line with the main website (i.e., a more modern display font with multiple weight variants).
It replaces some of the lighter text with a lighter weight, thus maintaining a similar "visual weight", which is what the main site does.
It also makes the docs font follow the main site font.
Once again, this change is open to discussion.
Comparison below:
> Web change main font

- web/index.html
- web/style.css
- web/theme-4.css
This PR mainly removes "ExaWorks" from the logo. It also:
- makes the navbar smaller
- switches the copyright owner from "ExaWorks" to "The ExaWorks Project" and changes it to a link pointing back to exaworks.
- changes the HTML title from "PSI/J" to "PSI/J - Python".
You can see a visual comparison of the logo/navbar changes below:
The existence of this PR does not assume that a decision has been made either way, so feel free to discuss.
> Web debranding

- docs/programming.rst
- src/psij/executors/batch/cobalt.py
- src/psij/executors/batch/lsf.py
- src/psij/executors/batch/pbspro.py
- src/psij/executors/batch/slurm.py
- src/psij/executors/flux.py
- src/psij/executors/local.py
- src/psij/executors/rp.py
- src/psij/job.py
- src/psij/job_executor.py
- src/psij/launchers/mpirun.py
- src/psij/launchers/srun.py
There is still work to do, I just think this is ready to go in and want to keep working on it later.
It is all docstring/docs changes except for one little tweak to ``Job.__str__()``.
> Docs: API guide

- web/index.html
- web/style.css
- web/theme-4.css
This PR changes the navbar items to a dark color for better contrast. It makes the red-ish side of the navbar gradient slightly lighter, for the same reason. 
As usual, this is open to discussion.
> Changed navbar item colors from white to black to improve visibility.

- web/index.html
- web/style.css
This PR changes the layout of some items on the front page. There were some suggestions that the old layout wasn't quite right. So this one splits the first line into two: the firs is a brief description of PSI/J with an image that illustrates that description. The second is the more detailed main card.
This is one possible layout out of many, so we can use this space to discuss other options.
->
> Update layout a bit

- docs/conf.py
- docs/index.rst
This PR makes the sidebar not be empty when going to the index page. It also increases the ToC depth to 3 on the index page.
> Web docs fix sidebar

- src/psij/executors/batch/batch_scheduler_executor.py
- src/psij/launchers/script_based_launcher.py
- src/psij/launchers/scripts/mpi_launch.sh
- src/psij/launchers/scripts/multi_launch.sh
- src/psij/resource_spec.py
- tests/_test_tools.py
- tests/conftest.py
- tests/plugins1/_batch_test/_batch_test.py
- tests/plugins1/_batch_test/test/hostname
- tests/plugins1/_batch_test/test/launcher.sh
- tests/plugins1/psij-descriptors/descriptors.py
- tests/test_executor.py
- tests/test_mpi.py
- tests/test_resources.py
This PR started as an effort to add more tests, particularly in the direction of resource specification/allocation.
It needed some local validation, so a test launcher was added that can fake multiple hosts.
As a side effect, ResourceSpecV1 was also revamped a bit: it made no sense that one couldn't specify, say `process_count=4` and `node_count=2`. That is now possible. ResourceSpecV1 checks basic constraints, such as `process_count % node_count = 0`, `process_count = node_count * ppn`. It can also infer some of these numbers if they are not otherwise specified. However, whether the inferred numbers are used or not by an executor is left to the executor.
> More tests

- LICENSE
Adding MIT License based on discussion at Exaworks workshop. We need a license to be on for pushing out a Pypi release.
With agreement from: @kylechard @danlaney @shantenujha @hategan and @rafaelfsilva
> Adding MIT license for release

- .github/workflows/python-package.yml
- setup.py
- src/psij/__init__.py
- src/psij/version.py
This PR splits out changes in #226 to support better version info handling.
* version info is now set in the module `src/psij/version.py`
* updates to `setup.py` to use the above
* `psij.__version__` will work now.
> Setup version info

- Makefile
- tag_and_release.sh
Adding deploy scripts and matching changes to the `Makefile`.
Here are the deploy steps I recommend:
1. Create a branch off of main once ready to deploy
2. Bump the version info, docs etc in the branch
3. Review and merge to main
4. Run the following to deploy from main 
```
make VERSION=<version_info> tag-and-release
```
The above call will make a github tag, and deploy to pypi, so make sure to have your pypi creds handy.
> Adding deploy scripts

- testing.conf
- tests/ci_runner.py
- tests/conftest.py
This PR adds the possibility of uploading minimal test results. This is best described by the corresponding text in `testing.conf`:
> Enables minimal uploads mode. In minimal mode, no information that is
> potentially sensitive is uploaded to the test results server. Specifically,
> only the following are uploaded:
>   - code related identifiers, such as branch names, class names, etc.
>   - times and dates
>   - test related identifiers, such as run id
>   - the maintainer email, if one is provided
>   - boolean values, such as whether the target system has mpirun available,
>     etc.
>   - git identifiers and counts: branch name, last commit hash, how many
>     commits the local code has ahead/behind of the remote, and if there
>     are any local changes
>   - the result status of …
> Minimal test uploads

- psij-ci-setup
This fixes #239.
To test, check out main, remove crontab files with `crontab -r` (don't do this if you have important stuff in your crontab; alternatively, do so under a test login). Then psij-ci-setup with cron should fail to produce a crontab and end with the error 'no crontab for <user>'.
The check out this branch, ensure no crontab again (`crontab -r`) and run psij-ci-setup. It should succeed (i.e., `crontab -l` should list the new job).
> Gracefully deal with missing crontabs rather than failing

- web/index.html
The minimum version was upgraded to 3.7 in PR #126 .
This is the last reference to 3.6 in the code base.
> web: fix minimum Python version

- docs/README-selectors.md
- docs/_static/extras.js
- docs/quickstart.rst
- web/docs/_static/cloud.css
You can now add an extra class to *-selector to make it show up as tabs.
> Doc selectors tab mode

- docs/conf.py
- web/lib.js
Firefox does not properly scroll to anchors in an iframe if the iframe is
very large. There appear to be similar issues in Firefox which can be fixed
by explicitly calling `scrollIntoView()` on the target element. This
solution appears to work here, too.
The problem manifests itself if you go to, e.g., the API ref for Cobalt and
try to either click on permalinks for the various methods or attempt to
navigate to the "See <base class method>" links.
> Fix firefox iframe scroll

- tests/ci_runner.py
*PLEASE DON'T MERGE AFTER REVIEW*
This PR is in preparation for renaming the repo to "psij-python". It is needed because existing tests deployments will continue to reference the old repo. This PR modifies the test runner to patch relevant files and update to the new URL automatically.
The plan, once this is reviewed, is as follows:
- merge this
- immediately:
- rename the repo
- clone the repo to also have a copy in the old location so that running tests can get the updated test runner
- (alternatively, we could clone the old repo, but it may be better to do a rename to ensure that all ancillary data -- e.g. wiki pages -- is preserved)
- add a warning to the clone (old URL) that the repo is not used any more and that existing checkouts should have their origin URLs updated
- archive the …
> Repo rename prep

- README-testing.md
- psij-ci-load
- psij-ci-run
- psij-ci-setup
psij-ci-env. Psij-ci-run still attempts to load it if it's there just in case.
> Removed mentions of psij-ci-load since it has been phased out by

- tests/ci_runner.py
- tests/conftest.py
`store_true` for argparse doesn't actually look at value, only at presence,so `--option=false` is the same as `--option` and `--option=true`.
`store` only stores strings, so tests like `if minimal` would succeed for `--minimal-uploads=false`.
> Fix parsing of boolean config options, such as minimal_uploads.

- tests/ci_runner.py
an different way of getting the same information which is hopefully more widely supported.
Fixes #306.
> Old versions (<2.0) of git don't have `git remote get-url`. This uses

- README-dev.md
This is one potential release process, that gives you some guarantees of clean history given the volume of activity. I suspect that this might need some discussion before we are agreed on this.
Once this goes in, we can discuss whether it makes sense to do further automation, say once a tag is minted of a regex pattern, github action will do the push to pypi. I'm unsure of how safe this is because the multi-site testing infrastructure is completely separate from github actions and might need some human intervention to confirm everything is green.
> Adding release instructions

- src/psij/executors/flux.py
Filter jobs based on user ID (implicit in default
argument) and job states. Only fetch job id attribute.
Fixes #324.
> flux executor: fix broken list method

- requirements-dev.txt
errors for things used in type annotations and docstrings.
> Downgrading flake8 to 5.x since 6.x messed up and is producing F401

- CONTRIBUTING.md
those who have write access to the repo and it is unnecessary for those. It is also implied for those who do not have write access to the repo (i.e., there is no other choice than to create a fork). So long story short, I don't think that part was necessary, enforced, or particularly useful.
> Removed the creating your own fork part. It has not been followed by

- src/psij/job_executor.py
Spent one hour on the tutorial trying to figure out why my job was completed before the output was generated. Well, it's because it was a previously completed job that was being submitted again, but wait() didn't know that.
> Check that the job is in a new state before submitting.

- README-dev.md
- web/Gemfile
- web/README.md
- web/_config.yml
The previous incantation of the web stuff used the latest version of Jekyll. However, gh-pages uses an older version, and that conflicts with the supplied gemfile. Additionally, it processes the configuration (includes/excludes) differently, so this PR also updates the jekyll configuration file.
And last, this updates the relevant README files to reflect the changes above.
> More ghpages fixes

- docs/README-selectors.md
- docs/_static/extras.js
- docs/getting_started.rst
- tests/test_getting_started_docs.py
This basically also allows references of the form `execparams.executor` to be substituted using selectors. That, in turn, would
allow one to include test cases verbatim while preserving the selector behavior.
> Docs selectors for testing

- Makefile
This makefile command will generate HTML coverage-reports that you can browse through locally.
> Makefile: included html-coverage-report command

- web/docs/_static/cloud.css
On large displays (with width >>14in), when viewing the documentation pages, the padding kicks in. It is meant to shift the text towards the center while preserving the width of the main text (through the max-width property). However, the padding is part of the width, so it ends up reducing the usable text width.
We could switch to controlling the margin, but then the thin left border also moves, which is unpleasant. I guess we could do that AND have the sidebar draw the border, but that's two steps.
So anyway, this adjusts the max-width to take the padding into account.
This addresses https://github.com/ExaWorks/exaworks.github.io/issues/5
PS: checks fail due to #362
> Fix text squeezing on large displays.

- requirements.txt
Also pins filelock and psutil to known working major versions.
Fixes #362
> Pin typeguard version to 2.xx.

- README-dev.md
- docs/conf.py
Some updated release instructions as well as the docs version using the psij version rather than a manual string.
This PR is a post-release update (i.e., the 0.9 release is done and it does not depend on this PR). However, the online docs still show "0.1.0-post1" as the version until this PR is merged.
> Some release related updates

- web/404.html
- web/_includes/vueinit.html
- web/versioning.js
Also added code to detect if the 404 is on a documentation page. The version switcher in the documentation attempts to preserve the path (so that if you are looking at, say, JobExecutor in a version, you'd also potentially be looking at JobExecutor after the switch). However, there is no guarantee that the docs structure is the same in the two versions, so you may land on a page that's not there. The code looks at whether you are hitting a 404 on a docs page and offers a link to the main docs page for that version.
Also, a minor fix in `getCurrentVersion`
> Fix 404 page (missing tabs property was making it render funny).

- testing.conf
- tests/ci_runner.py
This changes the test upload url in testing.conf to testing.psij.io (which is now live).
It also updates ci_runner.py to patch testing.conf on systems where the tests are already set up.
And ci_runner.py now has a slightly nicer way of applying such patches.
> Patch testing url

- src/psij/executors/local.py
stall new jobs from being submitted. Instead, make a copy of the jobs dict and operate on that without holding the lock.
This seems to make the local executor faster (!) than plain Popen + wait, which I can't say I understand clearly.
> Don't hold the reaper lock while checking processes, since it can

- docs/getting_started.rst
The current `Install from pip` instruction in the Getting Started page of the documentation is:
```
pip install psij
```
which should instead be:
```
pip install psij-python
```
> Fix `Install from pip` instruction in getting started page of documentation

- src/psij/executors/local.py
import. It also solves some problems with starting jobs from subprocesses.
However, a better solution for making things work properly in both parent process and subprocesses when fork is involved is to associate singleton threads with process IDs.
> Attach signal handler when starting reaper to avoid starting reaper on

- tests/test_doc_examples.py
we may end up skipping some jobs and submitting some twice.
> Properly synchronize before incrementing current_job_index, otherwise

- src/psij/job_executor.py
executor property is already set (which would indicate that it was submitted before).
> Added a simple check in `JobExecutor.submit()` to test if a job's

- src/psij/executors/batch/batch_scheduler_executor.py
attaching a job to a native job.
> Don't clean up submit file if it doesn't exist, which is the case when

- QuickStart.md
- README-dev.md
- docs/api.rst
- docs/development/programming.rst
- docs/development/tutorial_add_executor.rst
- docs/getting_started.rst
- docs/index.rst
- docs/user_guide.rst
- web/about.html
- web/index.html
Changes are spread across multiple documents. Most are optional but tighten up the language a bit.
**QuickStart.md**
- Standardized spelling/capitalization of PSI/J when not part of code.
- Updated Hello World capitalization
**README-dev.md**
- Line 1: Removed previous h1, which didn't add clarity. This required subsequent changes to other headers (bumping them up a level).
**docs/api.rst**
- Overall: Streamlined content; most edits are optional but tighten up the language a bit.
- Lines 8, 29, 56, 147, 219, 227: Promoted a header to an h2 from an h3.
- Lines 102, 108, 114, 120, 126, 132, 128, 177, 184, 191, 198, 205, 212: Demoted headers from h3s to h4s.
**docs/development/programming.rst**
- Overall: Streamlined content; most edits are optional but tighten up the language a bit.
- Lines …
> Llnl edits

- src/psij/job_spec.py
- tests/test_job_spec.py
Currently, the various path kwargs in `JobSpec`, such as `directory` and `stdout_path`, require the user to input them as `Path` objects. It would arguably be more convenient to allow the user to pass in any `PathLike` object, particularly a `str` representation. This PR simply calls `Path()` on these kwargs to automatically convert them to `Path` objects if they aren't already.
> Allow for `str` paths as inputs to `JobSpec`

- src/psij/executors/batch/batch_scheduler_executor.py
- src/psij/executors/batch/cobalt.py
- src/psij/executors/batch/cobalt/cobalt.mustache
- src/psij/executors/batch/lsf.py
- src/psij/executors/batch/lsf/lsf.mustache
- src/psij/executors/batch/pbspro.py
- src/psij/executors/batch/pbspro/pbspro.mustache
- src/psij/executors/batch/script_generator.py
- src/psij/executors/batch/slurm.py
- src/psij/executors/batch/slurm/slurm.mustache
- tests/plugins1/_batch_test/_batch_test.py
- tests/plugins1/_batch_test/test/test.mustache
- tests/test_executor.py
This adds a test that sets various string properties of the job spec tree to some random value and then checks the generated submit script for that value.
It also fixes #416. It is unclear what causes #416 to happen, since there are no code changes in psij that are related. The one possible explanation is that pystache became more strict on processing keys and will not make a global lookup if the current dictionary is missing a key.
As a result of this test, a few more attributes that were missing in various executors are now added. It is somewhat unclear what the benefits of some of these additions are (PBS uses special queue names for reservations rather than requiring some reservation id attribute on the job, like Slurm or LSF, so arguably one does not need to handle the reservation_id …
> Test submit script generation basics

- web/index.html
Actually, a bunch of typos. Be wary of the github suggestions interface. It can be deceiving in terms of what the scope of the change is.
Fixes #417.
> Fixed typo

- src/psij/__init__.py
- src/psij/exceptions.py
- src/psij/job.py
- src/psij/job_state.py
- tests/test_wait.py
greater than `target_states` not just for `target_states`).
This goes a bit further by also implementing the yet-to-be-merged updates from https://github.com/ExaWorks/job-api-spec/pull/178
> Properly implement wait according to spec (i.e., wait for all states

- src/psij/executors/flux.py
Update `flux.py` to fix the following error: `AttributeError: module 'flux' has no attribute 'jobspec'`
> fix `AttributeError: module 'flux' has no attribute 'jobspec'`

- tests/conftest.py
Contrary to popular belief, python does not automatically expand `~` in pathlib.PosixPath objects.
> Fix new key lookup

- docs/_static/extras.js
- docs/user_guide.rst
- tests/getting_started/test_simple_example.py
- tests/test_nodefile.py
- tests/user_guide/test_resourcespec.py
- tests/user_guide/test_scheduling_information.py
This basically makes sure that `_get_executor_instance` is used when potentially dealing with queuing systems. This is done in order
to propagate various job attributes from testing.conf.
It also updates the web rendering library to recognize when a doc example has `_get_executor_instance(...)` and replace with something more palatable.
> Some testing fixes

- psij-ci-setup
It also fixes a broken test for the authentication key.
> Make cron test installation work even when the user's crontab is empty.

- tests/conftest.py
This allows https://github.com/ExaWorks/psij-testing-service/pull/67 to show schedulers other than Slurm and enables actual testing of the scheduler on machines other than ones with Slurm.
> Add (lousy) detection of schedulers other than Slurm.

- requirements-docs.txt
breaks Sphinx 4.5 who doesn't pin the dep to something compatible with it.
It's even more silly because we don't generate applehelp output.
> sphinxcontrib-applehelp 1.0.8 added a requirement for Sphinx 5.0, which

- docs/user_guide.rst
- tests/_test_tools.py
- tests/test_executor.py
- tests/user_guide/test_prelaunch.py
to not complain of a null spec when checking an attached job.
> Use `assert_completed` when possible and also change `assert_completed`

- testing.conf
- tests/ci_runner.py
- tests/conftest.py
- tests/executor_test_params.py
The motivation here is that, on Perlmutter, it's a wise idea to run most tests on shared nodes (since we don't want to burn too fast through a small allocation). However, some tests, such as tests that verify that multi-node jobs run on multiple nodes, will fail since the shared node mode (--qos=shared) does not allow for multi-node jobs. So there needs to be a way to use a different --qos parameter for certain tests.
> Added a way to specify test filters for custom attributes.

- src/psij-descriptors/pbs_descriptor.py
- src/psij-descriptors/pbspro_descriptor.py
- src/psij/executors/batch/pbs.py
- src/psij/executors/batch/pbs/pbs_classic.mustache
- src/psij/executors/batch/pbs/pbspro.mustache
- src/psij/executors/batch/pbs_base.py
- src/psij/executors/batch/pbs_classic.py
- tests/test_executor.py
Also split PBS executor into pbs_classic (the one using `:ppn` to specify processes per node) and the modern pbspro/openpbs (using `select=:ncpus=`).
Fixes #434
> Added resource specs to PBS executor, which were somehow missing.

- src/psij/executors/batch/slurm/slurm.mustache
assumptions about how the process worked that were incorrect. Specifically, you cannot issue multiple `#SBATCH --export` directives and expect them to add up. Only one should be used.
> Fixed handling of env vars in Slurm. The existing template made some

- src/psij/executors/batch/batch_scheduler_executor.py
was only done in the local executor.
> Detect launcher failure in the batch scheduler executors. Somehow this

- src/psij/executors/batch/slurm/slurm.mustache
`scontrol show hostnames` only shows one line per node, no matter how many processes we requested. In order to bring this in line with the uniform PBS way of doing things (one line per process in the nodefile, possibly with duplicate entries), we need to do some manual work.
This also further fixes environment variable processing. Variables were set before the `#SLURM --export` directives, which means that the latter were effectively ignored by Slurm which stop processing once anything non-comment is found in the script.
> Fix slurm nodefiles

- docs/user_guide.rst
- tests/_test_tools.py
- tests/test_nodefile.py
- tests/user_guide/test_prelaunch.py
except that the ci_runner, when testing various branches, does the cloning in `/tmp`. One alternative solution would be to ensure this is moved to the home dir.
This was basically why `test_prelaunch` and `test_nodefile` failed.
> Files used by jobs need to be on a shared FS. This is typically the case

- tests/user_guide/pre_launch.sh
- tests/user_guide/test_prelaunch.py
I haven't quite figured out how, but the actual module command, on systems in which it is present, has some uncanny ability of replacing the one you exported when a new instance of bash is launched. So, on systems on which module is actually available, this test fails. Renaming the function should fix it.
> Fix preload test on systems with the module tool installed

- src/psij/executors/batch/batch_scheduler_executor.py
ignore FileNotFoundError instead
See test_executor::test_attach2[slurm:srun on [https://testing.psij.io/run.html?...](https://testing.psij.io/run.html?site_id=perlmutter.nersc.gov&run_id=2024022406-3ac2618e18df98e9eedf6f962587213e5f3e24a41076615c4973d544da9972ea#branch-main) for the failure.
> Checking existence and then deleting is not atomic, so try to delete and

- .gitignore
- docs/conf.py
- docs/development/tutorial_add_executor.rst
- requirements.txt
- src/psij-descriptors/aprun_descriptor.py
- src/psij-descriptors/cobalt_descriptor.py
- src/psij-descriptors/core_descriptors.py
- src/psij-descriptors/flux_descriptor.py
- src/psij-descriptors/jsrun_descriptor.py
- src/psij-descriptors/lsf_descriptor.py
- src/psij-descriptors/pbs_descriptor.py
- src/psij-descriptors/rp_descriptor.py
- src/psij-descriptors/slurm_descriptor.py
- src/psij-descriptors/srun_descriptor.py
- src/psij/_plugins.py
- src/psij/descriptor.py
- tests/plugins1/psij-descriptors/descriptors.py
- tests/test_executor_versions.py
is deprecated in Python 3.1x ish.
> Use packaging.versions insted of distutil.version, since the latter

- tests/ci_runner.py
We don't want a dependency to install something that may have the same name as something in psij (including possibly a different version of psij itself) and hijack things.
@andre-merzky: We have a bit of a circular dependency: psij -> rp -> psij. This should be fine, since psij -> some_pilot_system -> psij is one of the intended scenarios. We may want to discuss whether such dependencies are necessarily package dependencies.
> When testing, always put the src dir before .packages in PYTHONPATH. 

- QuickStart.md
- docs/_static/extras.js
- docs/user_guide.rst
- src/psij/executors/batch/cobalt/cobalt.mustache
- src/psij/executors/batch/lsf/lsf.mustache
- src/psij/executors/batch/pbs/pbs_classic.mustache
- src/psij/executors/batch/pbs/pbspro.mustache
- src/psij/executors/batch/slurm/slurm.mustache
- src/psij/job_attributes.py
- testing.conf
- tests/_test_tools.py
- tests/ci_runner.py
- tests/conftest.py
- tests/executor_test_params.py
- tests/plugins1/_batch_test/test/test.mustache
- tests/test_executor.py
- tests/user_guide/test_scheduling_information.py
Deprecate the `project` attribute and re-direct it to `account`.
Fixes #456.
> Added `account` job attribute to use for accounting/billing.

- MANIFEST.in
- release.sh
- setup.py
This PR ensures that `requirements.txt` is available in source release packages so that psij can be installed from those.
It also adds some minor fixes to the release/setup scripts.
Fixes #466
> Requirements in release

- .github/workflows/codespell.yml
method, so add it to the codespell ignore list.
> Newer versions of codespell seem to get triggered on pytest's assertIn

- src/psij/executors/batch/cobalt/cobalt.mustache
- src/psij/executors/batch/lsf/lsf.mustache
- src/psij/executors/batch/slurm/slurm.mustache
- src/psij/job_executor.py
- src/psij/resource_spec.py
- tests/plugins1/_batch_test/test/test.mustache
- tests/test_executor.py
Some scheduler configurations (e.g., Frontier@ORNL) require a node count. We do not mandate one, with the assumption that schedulers will have defaults and, if not, the (possibly misguided) spirit of PSI/J being a pass-through device which lets the scheduler decide how to handle a missing node count specification is maintained.
The problem exists when either a resource spec is missing and when the resource spec only specifies a process count (because the Slurm template does not use the computed counts).
This breaks our tests on Frontier. That, in itself, could be a statement that our tests are broken and should always specify a node count. More importantly, however, this breaks abstraction.
The point is that if we avoid defining defaults in PSI/J under the assumption that the scheduler …
> Use default values for resource requests

- .github/dependabot.yml
- .github/workflows/python-package.yml
- .mypy
- QuickStart.md
- docs/getting_started.rst
- requirements.txt
- setup.py
- src/psij/serialize.py
- web/install.html
> Removed dependency on typing_compat and bumped the minimum python

- src/psij/executors/batch/batch_scheduler_executor.py
This fixes #501 by replacing the executor property of _QueuePollThread by weakref and shutting down the thread when
the executor is collected. The weak ref is necessary to avoid a reference loop which would prevent a `__del__` based solution from working.
> Fix thread "leak"

- testing.conf
- tests/_test_tools.py
- tests/ci_runner.py
- tests/executor_test_params.py
If specified, this option allows multi-node tests to run using a different queue than the one in `queue_name`. The wisdom of this is that on certain systems it makes sense to use more restrictive but less expensive queues by default, and only use more expensive, multi-node queues when strictly needed. In a sense, this could be hacked using `custom_attributes` and test filters, which some deployments do, but it is awkward and difficult to set up in a way that predicts all future multi-node tests.
When merged, the new `ci_runner.py` will automatically be used by all deployed tests. It was modified to not pass config
options that are not set, and all such options should have defaults in the `conftest.py` arg parser, both old and new.
This addition will affect tests that are currently …
> Adds a `multi_node_queue_name` ci config option

- src/psij/launchers/scripts/mpi_launch.sh
mpirun, on some systems, can print "helpful messages". Except they aren't
helpful for us trying to run automated systems with predictable behavior.
> Add "quiet" flag for mpirun to avoid messages interfering with output capture.

- tests/test_executor.py
On some machines, the tests use a fast queue for simple jobs that only allow one (or a small number of) job(s) to be queued at a time. If we don't wait for the job to complete, the next job may lead to a violation of queue policies.
> Wait for job to complete in `test_list`

- src/psij/launchers/script_based_launcher.py
- src/psij/launchers/scripts/mpi_launch.sh
- tests/_test_tools.py
- tests/test_executor.py
On delta.ncsa, mpirun produces various diagnostic output along with the application stdout. This output is not suppressed by the `-v` parameter to mpirun. Instead, we can use output tagging, which marks each application output line with `[jobid, rank]<stdxxx>:...`.
The PR also fixes launcher error reporting as well as adds a test for stderr redirect.
> Better extraction of stdout/stderr streams from mpirun

- src/psij/launchers/scripts/mpi_launch.sh
Of course, the saga is not over.
When specifying `--tag-output`, mpirun is supposed to "tag each line" with `[jobid, rank]<stdxxx>:`. It mostly does. However
it occasionally does something else. Assume that `a.txt` and `b.txt` contain `ABCD` and `EFGH`, respectively. Running
`mpirun --tag-output -n 1 cat a.txt b.txt` mostly produces 
```
[1,0]<stdout>:ABCDEFGH
```
Occasionally, the following shows up instead:
```
[1,0]<stdout>:ABCD[1,0]<stdout>:EFGH
```
That is indistinguishable from `b.txt` having contained `[1,0]<stdout>:EFGH`. This, my guess would be, is due to a brief delay between the files that `cat` introduces. This can be verified by adding more files for `cat` and seeing all kinds of combinations of tags popping out in the middle of a line.
One solution is to use heuristics and …
> mpirun can mangle tagged output lines, so use heuristics to fix that.

- src/psij/executors/batch/batch_scheduler_executor.py
When passing a plain `JobExecutorConfig` to a batch scheduler executor, the executor attempts to access various batch scheduler specific properties, which do not exist (see #511).
This PR checks if a vanilla `JobExecutorConfig` is passed to a batch scheduler executor and replaces it with a `BatchSchedulerExecutorConfig` while copying the relevant properties.
Fixes #511.
> Allow passing a vanilla JobExecutorConfig to batch scheduler executors

- src/psij/job_attributes.py
attribute to `None` due to the setter. So only set if not the default.
> Setting the `project_name` in the constructor can reset the `account`

- src/psij/executors/batch/lsf/lsf.mustache
- src/psij/executors/batch/pbs/pbs_classic.mustache
- src/psij/executors/batch/pbs/pbspro.mustache
- src/psij/executors/batch/slurm/slurm.mustache
- src/psij/resource_spec.py
- tests/test_resources.py
Some deployments require a memory specification when using nodes in non-exclusive mode. This PR adds that feature.
> Add `memory` property to `ResourceSpecV1`

- src/psij-descriptors/nqsv_descriptor.py
- src/psij/executors/batch/nqsv.py
- src/psij/executors/batch/nqsv/nqsv.mustache
This pull request adds an executor that supports NQSV (https://www.nec.com/en/global/solutions/hpc/articles/tech08.html). This is a proprietary job scheduler developed by NEC and is used in multiple large-scale HPC systems in Japan.
To wait for the completion of a job, PSI/J currently polls the status of the job. Since NQSV offers a dedicated command (qwait ) to wait for a job, we have implemented job completion detection using qwait instead of polling.
We hope to discuss and refine the implementation based on your feedback. Once the PR is reviewed and approved, we will update the documentation accordingly.
> Add executor for NEC’s job scheduler (NQSV)

- src/psij/_plugins.py
- src/psij/job_spec.py
- tests/test_executor.py
- tests/test_job_spec.py
The newest version of mypy found some issues, one of which was an actual bug.
> Typing fixes
